<a href="https://colab.research.google.com/github/ian24365/DALC_Scala/blob/main/DALC_scalar4_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%83%80%EC%9E%85%EA%B3%BC_numpy%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 넘파이 패키지 불러오기

In [ ]:
# 넘파이 패키지를 불러오기 np로 줄여쓰기# 넘파이 패키지를 불러오기 np로 줄여쓰기
import numpy as np

## array 정의 및 생성

In [48]:
# 넘파이 array를 사용하여 a라는 변수에 1부터 10까지의 숫자 리스트 배열을 생성하기
data = [1,2,3,4,5,6,7,8,9,10]
a = np.array(data)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
#파이썬의 기본 range 함수와 비슷한 넘파이 range 함수를 사용하여 ndarray를 만들 수 있습니다:
ar1 = np.array([range(i, i+3) for i in data])
ar1

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12]])

## 배열 구성

In [55]:
# full 함수를 사용하여 b라는 변수에 2.71 수로 3 X 4 다차원 배열 만들기
ar4 = np.full((3,4),2.71)
ar4

array([[2.71, 2.71, 2.71, 2.71],
       [2.71, 2.71, 2.71, 2.71],
       [2.71, 2.71, 2.71, 2.71]])

In [57]:
# arrange 함수를 사용하여 c라는 변수에 0부터 10까지 짝수만 있는 배열 구성하기
ar5 = np.arange(0,11,2)
ar5

array([ 0,  2,  4,  6,  8, 10])

In [59]:
# linespace 함수를 사용하여 d라는 변수에 0부터 1까지 4개 요소 값을 가진 배열 생성하기


ar7 = np.linspace(0,1,4)
ar7

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [60]:
# randint 함수를 사용하여 0 부터 100까지 수를 2 X 2 배열로 생성하기

ar8=np.random.randint(0,100,(2,2))
ar8

array([[19, 43],
       [70, 99]])

## 배열 인덱싱

In [79]:
# a변수에서 인덱스 2 (앞에서 3번째) 와 인덱스 -3 (뒤에서 3번째)에 해당하는 수 가져오기
a = np.arange(10)
a[2],a[-3]


(2, 7)

In [80]:
# a 변수에서 인덱스 3부터 9 까지 슬라이싱하기
a[3:10]

array([3, 4, 5, 6, 7, 8, 9])

## 배열 재구조화

In [64]:
#차원의 개수 알아보는 함수
import numpy as np

x = np.random.randint(10, size=(3,4,5))
print(x.ndim)

3


In [65]:
#차원의 크기 알아보는 함수
print(x.shape)

(3, 4, 5)


In [66]:
#전체 배열크기 알아보는 함수
print(x.size)

60


In [86]:
#0부터10까지 정수를 가진 x변수에서 4~7까지의 요소를 가진 하위배열생성
ar0 = np.arange(10)
ar0[4:8]

array([4, 5, 6, 7])

In [84]:
#0부터10까지 정수를 가진 x변수에서 첫번째 다섯 요소를 가진 하위 배열 생성
ar1 = np.arange(10)
ar1[:5]

array([0, 1, 2, 3, 4])

In [83]:
#0부터10까지 정수를 가진 x변수에서 인덱스 5 이후의 요소를 가진 하위 배열을 생성
ar = np.arange(10)
ar[5:]

array([5, 6, 7, 8, 9])

In [81]:
# 인덱스 0,1행과 인덱스 0,1,2열 즉 2행3열인 다차원 하위 배열 생성(콤마이용하기)
z=np.array([[3,4,5], [6,7,8]])
z

array([[3, 4, 5],
       [6, 7, 8]])

In [73]:
#1부터 10까지 배열을 3행3열로 재배열하기(reshape사용)
z = np.arange(1,10).reshape(3,3)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 배열 결합

In [70]:
#두개의 배열 결합하기
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.concatenate([x,y])
z

array([1, 2, 3, 3, 2, 1])

In [71]:
#수직으로 두개의 배열 결합하기
x = np.array([1,2,3])
grid=np.array([4,5,6]), [7,8,9]
v=np.vstack([x, grid])
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
#수평으로 두개의 배열 결합하기
y=np.array([[99], [99]])
z=np.hstack([grid, y])
z

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

## 배열 분할

In [69]:
#7개의 숫자를 가진 리스트 x를 3개의 변수 x1,x2,x3로 분할하기
x = [1,3,7,66,33,4,77]
x1,x2,x3 = np.split(x, [3,5])
print(x1,x3,x3)

[1 3 7] [ 4 77] [ 4 77]


In [68]:
#4행4열 차원을 배열이 상하 2개로 나누게 분할
grid = np.arange(16).reshape(4,4)
upper, lower=np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


# Numpy 심화

## 유니버셜함수

In [ ]:
# zeros 함수는 0으로 채워진 배열을 만듭니다:
np.zeros(5)

In [ ]:
#2D 배열(즉, 행렬)을 만들려면 원하는 행과 열의 크기를 튜플로 전달합니다. 예를 들어 다음은 3 \times 4 크기의 행렬입니다:

np.zeros((3,4))

In [ ]:
a = np.zeros((3,4))
a

In [ ]:
a.shape

In [ ]:
a.ndim # len(a.shape)와 같습니다

In [ ]:
a.size

In [ ]:
# 초기화되지 않은 2 \times 3 크기의 배열을 만듭니다(배열의 내용은 예측이 불가능하며 메모리 상황에 따라 달라집니다):

np.empty((2,3))

In [ ]:
#array 함수는 파이썬 리스트를 사용하여 ndarray를 초기화합니다:

np.array([[1,2,3,4], [10, 20, 30, 40]])

In [43]:
x = np.array([-10, -5, 0, 3, 7])
x
# x에 있는 배열을 모두 양의 정수로 반환하기

array([-10,  -5,   0,   3,   7])

In [ ]:
# 모두 양의 정수가 된 배열 x를 자연로그 배열로 반환하기

## 집계함수

In [ ]:
x=np.array([-2,-1,0,1,2])
"절댓값을 씌우려면?"
np.absolute(x)


In [ ]:
#삼각함수
theta = np.linspace(0,np.pi,3)
print("theta=" , theta)
print("cos(theta) =",np.cos(theta))
print("tan(theta)= ",np.tan(theta) ) 



In [ ]:
#역삼각함수
print("역 사인함수=",np.arcsin(theta))
print("역 코사인함수=",np.arccos(theta))
print("역 탄젠트함수=",np.arctan(theta)

In [ ]:
#로그함수
x=[1,2,4,10]
print("자연로그=",ln(x))
print("밑이2인 로그함수=",log2(x))
print("밑이 10인 로그함수=",log10(x))

In [ ]:
#지수함수
x=[1,2,3]
print("e^x=",np.exp(x))
print("2^x",np.exp2(x))
print("3^x=",np.power(3,x))

In [ ]:
#out 인자 
x=np.arange(5)
y=np.empty(5)
np.power(x,10,out=y)
print(y)

In [ ]:
#out 인자를 활용하여 배열 슬라이싱
x=np.arange(5)
y=np.empty(10)
np.power(2,x,out=y[::2])
print(y)

In [ ]:
#reduce 함수
x=np.arange(1,5)
np.add.reduce(x)

In [5]:
#sum,max,min함수
s=np.random.random(1000)
print("s의최솟값=", np.min(s))
print("s의최댓값=", np.max(s))


s의최솟값= 0.00017474244909776449
s의최댓값= 0.9996240567082771


In [ ]:
#axis 인자
"axis=0: 열기준 집계연산"
"axis=1: 행기준 집계연산"
"axis=none: 배열 내 모든 요소의 집계연산axis 인자"

In [ ]:
m= np.random.random((3,4))
print(m)

## 브로드캐스팅 연산

In [14]:
# 크기가 같은 어레이의 연산을 하기
 
x = np.array([1,2,3])
y = np.array([4,5,6])
x + y

array([5, 7, 9])

In [11]:
# 배열의 크기를 늘려서 연산하기
x = np.array([0,1,2])
M = np.ones((3,3))
x+M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## 비교연산자

In [15]:
# any 함수를 이용하여 하나라도 만족하면 true를 산출하는 코드만들기
x=np.arange(3)
np.any(x<-1), np.any(x<2)

(False, True)

In [16]:
# all함수를 이용하여 true산출 코드 만들기
x=np.arange(3)
np.all(x<-1), np.all(x<2)

(False, False)

In [19]:
# 1~5사이의 구간에서 5개 정수를 무작위로 발생시켜 1차원배열 2개변수를 생성하고 이에대한 불리언 값 결과내기

a = np.random.randint(1,5,5)
b = np.random.randint(1,5,5)
print(a,b)
a == b

[1 4 2 2 3] [4 1 1 4 3]


array([False, False, False, False,  True])

## 팬시 인덱싱

In [20]:
#배열을 생성하여 인덱싱하기
a = np.arange(10)
b = np.array([3,6,9])
a[b]

array([3, 6, 9])

In [26]:
#인덱스 값을 가진 2차원 배열(예를 들어 row=np.array([0,1,2]))을 이용하여 인덱싱
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
row = np.array([0,1,2])
col = np.array([2,1,3])

x[row,col]

array([ 2,  5, 11])

## 정렬 

In [31]:
#np.sort함수를 이용하여 복사하기
x = np.array([3,6,2,1,4,7])
print(x,np.sort(x))

[3 6 2 1 4 7] [1 2 3 4 6 7]


In [32]:
#변수.sort함수를 이용하여 정렬하기
x = [7,3,2,5,8,9]
x.sort()
print(x)

[2, 3, 5, 7, 8, 9]


In [33]:
#np.argsort함수 이용하여 정렬 요소의 인덱스를 반환하기
x = np.array([2,6,4,8,9])
i = np.argsort(x)
print(i)

[0 2 1 3 4]


In [34]:
#x_reverse를 이용하여 내림차순
x=np.array([4,7,2,3,1])
x_reverse = np.sort(x)[::-1]
print(x_reverse)

[7 4 3 2 1]


In [41]:
#axis를 이용하여 각 열을 기준으로 정렬하기
X = np.array([[3,2,1],
             [5,4,6],
             [6,9,7]])
np.sort(X,axis=0)

array([[3, 2, 1],
       [5, 4, 6],
       [6, 9, 7]])

In [40]:
#axis를 이용하여 각 행을 기준으로 정렬하기
X = np.array([[3,2,1],
             [5,3,8],
             [6,7,2]])
np.sort(X,axis=1)

array([[1, 2, 3],
       [3, 5, 8],
       [2, 6, 7]])