<a href="https://colab.research.google.com/github/ian24365/DALC_Scala/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2-1 데이터 구조와 넘파이 기초


In [ ]:
import numpy as np

In [ ]:
data1 = [1,2,3,4,5]
data2 = [6,5,4,3,2,1]
print(data1, data2)

[1, 2, 3, 4, 5] [6, 5, 4, 3, 2, 1]


In [ ]:
 ar1 = np.array(data1)
 ar1

array([1, 2, 3, 4, 5])

In [ ]:
#데이터타입 지정
 ar2 = np.array(data1, dtype='float32')
 ar2

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
 # 다차원 배열 구성
 ar3 =np.array([range(i, i+3) for i in data1])
 ar3
# 5x3행렬 생성됨

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [ ]:
# full 함수 (행렬크기, 지정값)
ar4=np.full((3,5), 3.14)
ar4
# 3X5

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
ar5 = np.arange(0, 20, 2)
ar5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#linspace 함수는 0.5 간격을 가진다.
ar6=np.linspace(0, 1, 3)
ar6

array([0. , 0.5, 1. ])

In [ ]:
#random 함수는 행렬의 크기를 지정하고  0, 1사이의 무작위 값의 배열 구성
ar7=np.random.random((3, 3))
ar7

array([[0.7427382 , 0.42173034, 0.27139589],
       [0.41797424, 0.67804188, 0.85275808],
       [0.99679918, 0.61979809, 0.22706421]])

In [ ]:
#randint함수는 지정된 값 사이의 무작위 값의  배열 생성
ar8=np.random.randint(0, 100,(3,3))
ar8

array([[25, 39, 90],
       [28, 31, 35],
       [76,  8, 72]])

In [ ]:
#eye함수는 대각선은 1이고 나머지는 0인 이차원 배열을 생성
ar9=np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 배열 분할, 재구성, 결합 => 효율적인 연산을 가능케 해줌줌
# 배열 속성/인덱싱/슬라이싱/재구조화/결합 및 분할

In [ ]:
import numpy as np
x = np.random.randint(10, size=(3,4,5))
x

array([[[3, 9, 9, 8, 4],
        [1, 5, 4, 1, 2],
        [8, 4, 3, 1, 9],
        [3, 1, 6, 7, 2]],

       [[1, 5, 1, 2, 2],
        [5, 3, 9, 1, 7],
        [6, 5, 0, 7, 7],
        [1, 8, 3, 5, 3]],

       [[5, 8, 5, 2, 6],
        [6, 6, 3, 8, 0],
        [3, 6, 0, 4, 7],
        [5, 2, 3, 6, 9]]])

In [ ]:
print("x ndim:", x.ndim) # 차원의 개수
print("x shape:", x.shape) # 차원의 크기
print("x size:", x.size)  # 전체 배열 크기

x ndim: 3
x shape: (3, 4, 5)
x size: 60


In [ ]:
y=np.array([2,4,6,8,10])
print(y[0], y[-2])

2 8


In [ ]:
  #다차원 배열 인덱싱
  z=np.array([[2,4,6,8,10], [3,6,9,12,15]])
  print(z)
  print(z[1, 0])

[[ 2  4  6  8 10]
 [ 3  6  9 12 15]]
3


In [ ]:
#인덱스 표기법으로 값을 수정 
 z [0, 0] =12
 z

array([[12,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [ ]:
# 배열 슬라이싱 

In [ ]:
# 콜론 (:) 기호 사용 (start:end:step) 기본값 0에서 부터 기본스텝은 1
x=np.arange(10)
x[4:8]

array([4, 5, 6, 7])

In [ ]:
x=np.arange(10)
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x=np.arange(10)
x[5:]

array([5, 6, 7, 8, 9])

In [ ]:
# 콤마(,)로 구분된 다중 슬라이스 표기법
z=np.array([[2,4,6,8],[3,6,9,12],[4,8,12,16]])
z
z[:2, :3]

array([[2, 4, 6],
       [3, 6, 9]])

In [ ]:
z=np.array([[2,4,6,8],[3,6,9,12],[4,8,12,16]])
z
z[:3, ::2]

array([[ 2,  6],
       [ 3,  9],
       [ 4, 12]])

In [ ]:
#배열 재구조화 

In [ ]:
#reshape함수
z=np.arange(1, 10).reshape(3, 3)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#배열 결합
#concatenate, vstack(수직), hstack(수평)
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.concatenate([x, y])
z

array([1, 2, 3, 3, 2, 1])

In [ ]:
x=np.array([1,2,3])
grid=np.array([[4,5,6], [7,8,9]])
v=np.vstack([x, grid])
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y=np.array([[99],[99]])
z=np.hstack([grid, y])
z

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

In [ ]:
#배열 분할
#split, vsplit, hsplit

In [ ]:
#split(분할 대상 리스트, 분할 위치(인덱스))
x = [1,2,3,77,77,3,2,1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [77 77] [3 2 1]


In [ ]:
 grid = np.arange(16).reshape(4,4)
 upper, lower=np.vsplit(grid,[2]) #grid 배열이 상하 2개로 나뉜다.
 print(upper)
 print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
 grid = np.arange(16).reshape(4,4)
 left, right =np.hsplit(grid,[2]) #grid 배열이 좌우 2개로 나뉜다.
 print(left)
 print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


2-2 넘파이 심화

In [ ]:
# 유니버설 함수
# 1. 단항 유니버설 함수 : 매개변수 하나만 갖는 함수
# 2. 이항 유니버설 함수 : 매개변수 두 개 갖는 함수수

In [ ]:
#삼각함수 (역삼각함수는 arcsin, arccos, arctan)
theta = np.linspace(0, np.pi, 3)
print("theta= ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta=  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
#지수함수//  로그함수는 ln(x), log2(x), log10(x)와 같이 표기
print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3,x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [ ]:
#out인자 : 지정한 배열에 직접 연산 결과 표기 가능
import numpy as np
x=np.arange(5)
y=np.zeros(10)
np.power(2,x,out=y[::2]) # 2씩 건너띈다.
print(y)
#대규모 연산의 경우 임시 배열을 생략하여 메모리와 연산시간 절감

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [ ]:
#집계연산 SUM, MIN, MAX

In [ ]:
#AXIS 인자 0:열기준, 1:행기준, none:배열 내 모든 요소소

In [ ]:
##브로드 캐스팅 연산
#서로 다른 크기의 배열에 이항 유니버설 함수를 적용할 수 있는 기능
#서로다른크기의 리스트끼리도 연산 수행이 가능능

In [ ]:
#크기가 같은 경우


In [ ]:
#스칼라 값을 더해야할 때 
 

In [ ]:
# 두 배열 브로드캐스팅

In [ ]:
#2차원 함수를 기반으로 이미지를 그릴 때

In [ ]:
##비교 연산자

In [ ]:
#any함수 : 하나라도 만족하면 true 산출

In [ ]:
all함수: 모두 만족해야 true 산출

In [ ]:
#팬시 인덱싱 : 인덱스배열을 인덱스로 사용하여 빠르게 활용 가능

In [ ]:
##정렬

In [ ]:
#sort함수: 원래 배열자체를 정리리